# in _config.yml
title: Curso Python
author: Alejandro Acosta León
year: 2023
logo: images/python-logo.png

# bibtex_bibfiles:
#     - /home/alejo/OneDrive/References/python-course.bib

execute:
  execute_notebooks: "auto"

repository:
  url                       : https://github.com/alejo-acosta/curso-python-ciee  # Online location of your book
  path_to_book              : /main/_build/html  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    suppress_warnings: ["mystnb.unknown_mime_type"]